version: '3.4'

volumes:
  SmartLibrarySQLDB:

services:
  dbsql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=guto@paiva22
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - SmartLibrarySQLDB:/var/opt/dbsql

  smartlibrary.api:
    image: ${DOCKER_REGISTRY-}smartlibraryapi
    build:
      context: .
      dockerfile: SmartLibrary.API/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - dbsql